name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Grant execute permissions for builder
      run: chmod +x build-versions.sh
    - name: Build with Gradle
      run: ./build-versions.sh
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          TeamCode-debug-mecanum.apk
          TeamCode-debug-programming-board.apk
          TeamCode-debug-inchworm.apk
          TeamCode-release-mecanum.apk
          TeamCode-release-programming-board.apk
          TeamCode-release-inchworm.apk
          
